set number
set nocompatible
set encoding=utf-8
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
filetype plugin indent on

" Key mappings
" CTRL-S to save
noremap <C-S>       :update<CR>
vnoremap <C-S>      <C-C>:update<CR>
inoremap <C-S>      <C-O>:update<CR>

" CTRL+Backspace to delete previous word
imap <C-BS> <C-W>
noremap! <C-BS> <C-w>
noremap! <C-h> <C-w>

" ALT+key window navigation
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

" Reload vim on all changes
augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

" Immediately set up and install vim-plug and plugins if they don't exist
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

" vim-plugged
call plug#begin('~/.vim/plugged')
runtime! module/**/*.vim
call plug#end()

set termguicolors
color dracula

autocmd vimenter * NERDTree

" Disable Netrw
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1
